name: todo
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3

  provider: ^6.0.1

  google_sign_in: ^5.2.1

  font_awesome_flutter: ^9.2.0

  cloud_firestore: ^3.1.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: RedHatDisplay
      fonts: 
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Black.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf

